config/routes.rb
Rails.application.routes.draw do
  
  resources :client_agents
  resources :mail_notification_settings
  resources :application_statuses
  resources :statuses
  # resources :lenders
  
  resources :clients do 
    get 'cases', on: :member
  end
  
  resources :applicants
  
  resources :contacts do 
    resources :contact_addresses
    resources :phone_numbers
  end
  
  resources :mortgage_addresses
  
  resources :case_requirements
  
  resources :requirements
  
  resources :notes
  
  resources :roles

  resources :application_cases do 
    resources :notes
    resources :case_requirements
    resources :applicants
    resources :application_statuses

    get 'edit_status', as: :edit_status
    get 'my_cases', as: :my_cases, on: :collection
    get '/search_agents' => 'application_cases#search_agents'
    post '/add_as_agent' => 'application_cases#add_as_agent' 
    get 'find_client', as: :find_client, on: :member
    post '/add_as_applicant' => 'application_cases#add_as_applicant'

  end

  resources :users do
    resources :application_cases
    resources :extra_details  
    resources :mail_notification_settings
    resources :client_agents
    resources :global_settings
    
    collection do 
      get 'clients_index',  as: :show_clients
      get 'agents_index',   as: :show_agents
    end
  end
  
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users, :path_prefix => 'my'

  # Additional users Routes
  get '/add_new_client' => 'users#add_new_client'

  # Additional Application Routes
  get '/client_cases' => 'application_cases#client_cases'
  get '/my_cases' => 'application_cases#index'
  get '/my_cases/:id' => 'application_cases#show'
  get '/new_case' => 'application_cases#new'
  get '/case_archive' => 'application_cases#case_archive'

  get '/search_users' => 'users#search_users'
  post '/add_as_client' => 'users#add_as_client'

  post '/send_email_notification' => 'notes#send_email_notification'
  post '/send_email_requirements_notification' => 'case_requirements#send_email_requirements_notification'


  get '/my_clients' => 'client_agents#index'

  # Root path
  root 'statics#index' 


end

app/models/client_agent.rb
class ClientAgent < ActiveRecord::Base
	belongs_to :client, :class_name => "User", :foreign_key => "client_id"
	belongs_to :agent, :class_name => "User", :foreign_key => "agent_id"

	scope :agents, -> (user) { where client_id: user.id }
	scope :clients, -> (user) { where agent_id: user.id }

end

app/controllers/client_agents_controller.rb
class ClientAgentsController < InheritedResources::Base
  before_action :set_client_agent, only: [:edit, :update, :destroy]
  before_action :set_user, only: [:new, :edit]

  def index
  	@client_agents = ClientAgent.clients(current_user)
  end

  def new
  	@client_agent = ClientAgent.new
  end

  def edit
   	
  end

  # POST /Contacts
  # POST /Contacts.json
  def create
    @client_agent = ClientAgent.new(client_agent_params)

    respond_to do |format|
      if @client_agent.save

	      ApplicationCaseMailer.added_as_agent(@client_agent.agent, @client_agent.client).deliver

        format.html { redirect_to @client_agent.client, notice: 'Agent was successfully added.' }
        format.json { render :show, status: :created, location: @contact_address }
      else
        format.html { render :new }
        format.json { render json: @client_agent.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /roles/1
  # PATCH/PUT /roles/1.json
  def update
    respond_to do |format|
      if @client_agent.update(client_agent_params)
        format.html { redirect_to @client_agent.client, notice: 'Agent was successfully updated.' }
        format.json { render :show, status: :ok, location: @contact_address }
      else
        format.html { render :edit }
        format.json { render json: @client_agent.errors, status: :unprocessable_entity }
      end
    end
  end


  # DELETE /notes/1
  # DELETE /notes/1.json
  def destroy
    @client_agent.destroy
    respond_to do |format|
      format.html { redirect_to @client_agent.client, notice: 'Agent was successfully removed.' }
      format.json { head :no_content }
    end
  end

  private

  	def set_user
  		@user = User.find(params[:user_id])
  	end

  	def set_client_agent
  	  @client_agent = ClientAgent.find(params[:id])
  	end

    def client_agent_params
      params.require(:client_agent).permit(:agent_id, :client_id)
    end
end

app/helpers/client_agents_helper.rb
module ClientAgentsHelper
end

app/views/client_agents/_form.html.erb
<%= form_for(@client_agent) do |f| %>
  <% if @client_agent.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@client_agent.errors.count, "error") %> prohibited this client_agent from being saved:</h2>

      <ul>
      <% @client_agent.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <%= f.hidden_field :client_id, :value => @user.id %>

  <div class="field">
    <%= f.label :agent_id %><br>
    <%= f.select :agent_id, User.agents.collect { |p| [ p.contact.full_name, p.id ] }, :prompt => 'Select One' %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/client_agents/edit.html.erb
<h1>Editing Client Agent</h1>

<%= render 'form' %>

<%= link_to 'Show', @client_agent %> |
<%= link_to 'Back', client_agents_path %>

app/views/client_agents/index.html.erb
<p id="notice"><%= notice %></p>

<h1>My Clients</h1>

<table>
  <thead>
    <tr>
      <th>Client</th>
      <th>Email</th>
      <th>Actions</th>
    </tr>
  </thead>

  <tbody>
    <% @client_agents.each do |client_agent| %>
      <tr>
        <td><%= client_agent.client.contact.full_name %></td>
        <td><%= client_agent.client.email %></td>
        <td class="actions">
          <%= link_to client_agent.client do %><i class="fa fa-eye fa-2x"></i><% end %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/client_agents/new.html.erb
<h1>New Client Agent</h1>

<%= render 'form' %>

<%= link_to 'Back', client_agents_path %>

app/views/client_agents/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Agent:</strong>
  <%= @client_agent.agent %>
</p>

<p>
  <strong>Client:</strong>
  <%= @client_agent.client %>
</p>

<%= link_to 'Edit', edit_client_agent_path(@client_agent) %> |
<%= link_to 'Back', client_agents_path %>