config/routes.rb
Rails.application.routes.draw do
  
  resources :client_agents
  resources :mail_notification_settings
  resources :application_statuses
  resources :statuses
  # resources :lenders
  
  resources :clients do 
    get 'cases', on: :member
  end
  
  resources :applicants
  
  resources :contacts do 
    resources :contact_addresses
    resources :phone_numbers
  end
  
  resources :mortgage_addresses
  
  resources :case_requirements
  
  resources :requirements
  
  resources :notes
  
  resources :roles

  resources :application_cases do 
    resources :notes
    resources :case_requirements
    resources :applicants
    resources :application_statuses

    get 'edit_status', as: :edit_status
    get 'my_cases', as: :my_cases, on: :collection
    get '/search_agents' => 'application_cases#search_agents'
    post '/add_as_agent' => 'application_cases#add_as_agent' 
    get 'find_client', as: :find_client, on: :member
    post '/add_as_applicant' => 'application_cases#add_as_applicant'

  end

  resources :users do
    resources :application_cases
    resources :extra_details  
    resources :mail_notification_settings
    resources :client_agents
    resources :global_settings
    
    collection do 
      get 'clients_index',  as: :show_clients
      get 'agents_index',   as: :show_agents
    end
  end
  
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users, :path_prefix => 'my'

  # Additional users Routes
  get '/add_new_client' => 'users#add_new_client'

  # Additional Application Routes
  get '/client_cases' => 'application_cases#client_cases'
  get '/my_cases' => 'application_cases#index'
  get '/my_cases/:id' => 'application_cases#show'
  get '/new_case' => 'application_cases#new'
  get '/case_archive' => 'application_cases#case_archive'

  get '/search_users' => 'users#search_users'
  post '/add_as_client' => 'users#add_as_client'

  post '/send_email_notification' => 'notes#send_email_notification'
  post '/send_email_requirements_notification' => 'case_requirements#send_email_requirements_notification'


  get '/my_clients' => 'client_agents#index'

  # Root path
  root 'statics#index' 


end

app/controllers/contact_addresses_controller.rb
class ContactAddressesController < ApplicationController
  before_action :set_contact_address, only: [:show, :edit, :update, :destroy]
  before_action :set_contact, only: [:new, :index, :show, :create, :edit, :update]

  def index
    @contact_addresses = @contact.contact_addresses.all
  end

  # GET /Contacts/1
  # GET /Contacts/1.json
  def show
  end

  # GET /Contacts/new
  def new
    @contact_address = ContactAddress.new
  end 

  # GET /Contacts/1/edit
  def edit
  end

  # POST /Contacts
  # POST /Contacts.json
  def create
    @contact_address = @contact.contact_addresses.build(contact_address_params)

    respond_to do |format|
      if @contact_address.save
        format.html { redirect_to @contact.user, notice: 'Address was successfully created.' }
        format.json { render :show, status: :created, location: @contact_address }
      else
        format.html { render :new }
        format.json { render json: @contact_address.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /roles/1
  # PATCH/PUT /roles/1.json
  def update
    respond_to do |format|
      if @contact_address.update(contact_address_params)
        format.html { redirect_to @contact_address.contact.user, notice: 'Address was successfully updated.' }
        format.json { render :show, status: :ok, location: @contact_address }
      else
        format.html { render :edit }
        format.json { render json: @contact_address.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /roles/1
  # DELETE /roles/1.json
  def destroy
    @contact_address.destroy
    respond_to do |format|
      format.html { redirect_to @contact_address.contact.user, notice: 'Address was successfully destroyed.' }
      format.json { head :no_content }
    end
  end



  private

    def set_contact
      @contact = Contact.find(params[:contact_id])
    end

  	def set_contact_address
  		@contact_address = ContactAddress.find(params[:id])
  	end

    def contact_address_params
      params.require(:contact_address).permit(:address_one, :address_two, :town, :county, :post_code, :primary, :user_id)
    end
end

app/helpers/contact_addresses_helper.rb
module ContactAddressesHelper
end

app/views/contact_addresses/_form.html.erb
<%= form_for([@contact, @contact_address]) do |f| %>
  <% if @contact_address.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@contact_address.errors.count, "error") %> prohibited this contact_address from being saved:</h2>

      <ul>
      <% @contact_address.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :address_one %>
    <%= f.text_field :address_one %>
  </div>
  <div class="field">
    <%= f.label :address_two %>
    <%= f.text_field :address_two %>
  </div>
  <div class="field">
    <%= f.label :county %>
    <%= f.text_field :county %>
  </div>
  <div class="field">
    <%= f.label :town %>
    <%= f.text_field :town %>
  </div>
  <div class="field">
    <%= f.label :post_code %>
    <%= f.text_field :post_code %>
  </div>
  <div class="field">
    <%= f.label :primary %>
    <%= f.check_box :primary %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/contact_addresses/edit.html.erb
<h2><%= @contact.full_name %></h2>
<h1>Editing Contact Address</h1>

<%= render 'form' %>

<%= link_to 'Show', [@contact, @contact_address] %> |

app/views/contact_addresses/index.html.erb
<h2><%= @contact.full_name %></h2>
<h1>Contact Addresses</h1>

<table>
  <thead>
    <tr>
      <th></th>
      <th>Address one</th>
      <th>Address two</th>
      <th>Town</th>
      <th>County</th>
      <th>Post code</th>
      <th colspan="3"></th>
    </tr>
  </thead> 

  <tbody>
    <% @contact_addresses.each do |contact_address| %>
      <tr class="<% if contact_address.primary? %>primary<% end -%>">
        <td><% if contact_address.primary? %><i class="fa fa-caret-right"></i><% end -%></td>
        <td><%= contact_address.address_one %></td>
        <td><%= contact_address.address_two %></td>
        <td><%= contact_address.county %></td>
        <td><%= contact_address.town %></td>
        <td><%= contact_address.post_code %></td>
        <td>
          <% if can? :update, @contact_address  %>
            <%= link_to edit_contact_contact_address_path(@contact, contact_address) do %><i class="fa fa-cog fa-2x"></i><% end %>
            <%= link_to [@contact, contact_address], method: :delete, data: { confirm: 'Are you sure?' } do %><i class="fa fa-times fa-2x"></i><% end %>
          <% end %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<% if can? :create, @contact_address  %>
  <%= link_to 'New Contact address', new_contact_contact_address_path(@contact) %>
<% end %>

app/views/contact_addresses/new.html.erb
<h2><%= @contact.full_name %></h2>
<h1>New Contact Address</h1>

<%= render 'form' %>

app/views/contact_addresses/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Address one:</strong>
  <%= @contact_address.address_one %>
</p>

<p>
  <strong>Address two:</strong>
  <%= @contact_address.address_two %>
</p>

<p>
  <strong>Town:</strong>
  <%= @contact_address.town %>
</p>

<p>
  <strong>Post code:</strong>
  <%= @contact_address.post_code %>
</p>

<p>
  <strong>Primary:</strong>
  <%= @contact_address.primary %>
</p>

<%= link_to 'Edit', edit_user_contact_address_path(current_user, @contact_address) %> |
<%= link_to 'Back', user_contact_addresses_path(current_user) %>