config/routes.rb
Rails.application.routes.draw do
  
  resources :client_agents
  resources :mail_notification_settings
  resources :application_statuses
  resources :statuses
  # resources :lenders
  
  resources :clients do 
    get 'cases', on: :member
  end
  
  resources :applicants
  
  resources :contacts do 
    resources :contact_addresses
    resources :phone_numbers
  end
  
  resources :mortgage_addresses
  
  resources :case_requirements
  
  resources :requirements
  
  resources :notes
  
  resources :roles

  resources :application_cases do 
    resources :notes
    resources :case_requirements
    resources :applicants
    resources :application_statuses

    get 'edit_status', as: :edit_status
    get 'my_cases', as: :my_cases, on: :collection
    get '/search_agents' => 'application_cases#search_agents'
    post '/add_as_agent' => 'application_cases#add_as_agent' 
    get 'find_client', as: :find_client, on: :member
    post '/add_as_applicant' => 'application_cases#add_as_applicant'

  end

  resources :users do
    resources :application_cases
    resources :extra_details  
    resources :mail_notification_settings
    resources :client_agents
    resources :global_settings
    
    collection do 
      get 'clients_index',  as: :show_clients
      get 'agents_index',   as: :show_agents
    end
  end
  
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users, :path_prefix => 'my'

  # Additional users Routes
  get '/add_new_client' => 'users#add_new_client'

  # Additional Application Routes
  get '/client_cases' => 'application_cases#client_cases'
  get '/my_cases' => 'application_cases#index'
  get '/my_cases/:id' => 'application_cases#show'
  get '/new_case' => 'application_cases#new'
  get '/case_archive' => 'application_cases#case_archive'

  get '/search_users' => 'users#search_users'
  post '/add_as_client' => 'users#add_as_client'

  post '/send_email_notification' => 'notes#send_email_notification'
  post '/send_email_requirements_notification' => 'case_requirements#send_email_requirements_notification'


  get '/my_clients' => 'client_agents#index'

  # Root path
  root 'statics#index' 


end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # -------------------------------------------
  # Associations

  belongs_to :role

  has_many :notes
  has_many :contact_addresses, :dependent => :destroy
  has_many :phone_numbers, :dependent => :destroy

  has_one  :extra_detail, :dependent => :destroy
  has_one  :mail_notification_setting, :dependent => :destroy
  has_one  :global_setting, :dependent => :destroy
  has_one  :client_agent, :dependent => :destroy, :foreign_key => "client_id"
  has_one  :contact, :dependent => :destroy

  has_many :brokered_cases, foreign_key: "user_id", class_name: "ApplicationCase"
  has_many :application_cases

  has_many :applicants, :dependent => :destroy
  has_many :application_cases, :through => :applicants

  has_many :clients, :dependent => :destroy
  has_many :customers, :through => :clients, :source => 'customer'

  # -------------------------------------------
  # scopes

  scope :clients, -> { joins(:role).where('roles.role = ?', 'Client') }
  scope :agents, -> { joins(:role).where('roles.role = ?', 'Agent') }
  scope :brokers, -> { joins(:role).where('roles.role = ?', 'Broker') }

  # -------------------------------------------
  # Callbacks

  after_create :build_contact
  after_create :add_extra_details
  after_create :create_mail_setting
  after_create :add_global_settings

  after_destroy :remove_as_client

  
  # -------------------------------------------
  #  User functions

  # check if Broker
  def is_broker?
    self.role.role == "Broker";
  end

  def has_contact_info?
     !!self.contact
  end

  def get_agent(user)
    @agent = ClientAgent.agents(user).first
    if !@agent.nil?
      return @agent.agent.contact.full_name 
    end
  end

  def get_broker
    client = Client.where_client_is(self).first
    @broker = User.find(client.user_id)
  end

  # check if Agent
  def is_agent?
    self.role.role == "Agent";
  end

  # check if Client
  def is_client?
    self.role.role == "Client";
  end

  def is_broker_of? (user)
    self.customers.include?(user)
  end

  def has_opted_out_of? (notifcation_type)
    @mail_setting = self.mail_notification_setting
    if @mail_setting.all_emails == true
      return true
    else
      @mail_setting.public_send(notifcation_type) == true
    end
  end

  def self.search(search)
    if search
      self.where('email LIKE ?', "#{search}")
    else
      # Do nothing
    end
  end

  def add_as_client(client, broker)
    broker.clients << Client.create(:user_id => broker.id, :client_id => @client.id )
  end

  def is_current_user?(user)
    self == user
  end

  def has_agent_and_is?(user)
    @agents = ClientAgent.agents(self)
    if @agents.any?
      @agent = ClientAgent.agents(self).first
      @agent.agent != user
    else
      return false
    end
  end

  private

    def remove_as_client
      @clients = Client.where_client_is(self)
      @clients.destroy_all
    end

    # Sets default role
    def build_contact
      @contact = Contact.create(:user_id => self.id, :fname => "Firstname", :lname => 'Lastname' );
      self.update_attributes(:contact_id => @contact.id)
    end

    def add_extra_details 
      if !self.is_client? 
        @extra = ExtraDetail.create(:user_id => self.id, :branch => '', :logo => '')
      end
    end

    def add_global_settings 
        GlobalSetting.create(:user_id => self.id, :color_one => '', :color_two => '', :color_three => '')
    end

    def create_mail_setting
        MailNotificationSetting.create(:user_id => self.id, :notes => true, :all_emails => true, :daily_digest => true, :status_update => true)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /roles
  # GET /roles.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show

    @contact_addresses = @user.contact.contact_addresses
    @extra = @user.extra_detail
    @numbers = @user.contact.phone_numbers
    @agent = ClientAgent.agents(@user).first
    @global_setting = @user.global_setting

    if current_user != @user 
      if !current_user.is_broker_of?(@user) && @user.has_agent_and_is?(current_user)
        flash[:notice] = "You can't see this, Sorry";
        redirect_to(application_cases_path);
      end
    end

  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1
  # GET /users/1.json
  def clients_index
    @clients = User.clients
  end

  def search_users
    @users = User.search(params[:search])
    @clients = current_user.clients
  end

  def my_clients
    if current_user.is_broker?
      @clients = current_user.clients
    end
    if current_user.is_agent?
      @clients = current_user.clients
    end
  end
    # GET /users/1
  # GET /users/1.json
  def add_new_client
    @role = Role.where(:role => 'Client').pluck(:id);
    @user = User.new
  end

  def add_as_client
    current_user.clients << Client.create(:client_id => params[:client_id] )
    redirect_to(clients_path);
  end

  # GET /users/1
  # GET /users/1.json
  def agents_index
    @agents = User.agents
  end

  def add_new_agent
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)
    @user.password = Devise.friendly_token.first(8)
    @password = @user.password
    respond_to do |format|
      if @user.save

        if current_user.is_broker?
          current_user.clients << Client.create(:user_id => current_user.id, :client_id => @user.id )
          
          # send password to user 
          ApplicationCaseMailer.new_user_and_password_notification(@user, current_user, @password).deliver
        else 

          ApplicationCaseMailer.new_user_and_password_notification(@user, current_user, @password).deliver
        end  
        format.html { redirect_to @user, notice: 'user was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /roles/1
  # PATCH/PUT /roles/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'user was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /roles/1
  # DELETE /roles/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'user was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    def user_params
      params.require(:user).permit(:email, :password, :password_confirmation, :role_id)
    end
end

app/views/users/_client_form.html.erb
<h2>Registration Details</h2>

<%= link_to 'Find existing user', search_users_path %><br><br>

<%= form_for(@user) do |f| %>

  <div class="field">
    <%= f.label :email %>
    <%= f.email_field :email, autofocus: true %>
  </div>

  <div class="field">
    <%= f.hidden_field :role_id, :value => @role %>
  </div>

  <div class="actions">
    <%= f.submit "Sign up client" %>
  </div>

<% end %>

app/views/users/_form.html.erb
<h2>Sign up</h2>

<%= form_for(@user) do |f| %>

  <div class="field">
    <%= f.label :email %>
    <%= f.email_field :email, autofocus: true %>
  </div>

  <div class="actions">
    <%= f.submit "Sign me up!" %>
  </div>

<% end %>

app/views/users/add_new_client.html.erb
<h1>New Client</h1>

<%= render 'client_form' %>

app/views/users/my_clients.html.erb
<p id="notice"><%= notice %></p>

<h1>My Clients</h1>
<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Name</th>
      <th>Mobile</th>
      <th>Email</th>
      <th>Address</th>
      <th>Cases</th>
      <th>Actions</th>
    </tr>
  </thead>

  <tbody>
    <% @clients.each do |client| %>
      <tr>
        <td><%= client.customer.contact.title %></td> 
        <td><%= client.customer.contact.full_name %></td>
        <td>Phone</td>
        <td><%= client.customer.email %></td>
        <td>Address</td>
        <td><%= link_to 'Cases', client_cases_path(:client => client.customer) %></td>
        <td><%= link_to 'Show', client.customer %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New client', add_new_client_path %>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form' %>

app/views/users/search_users.html.erb
<h2>Search and add Clients</h2>

<p>Enter email address</p>

<%= form_tag search_users_path, :method => 'get' do %>
  <p>
    <%= text_field_tag :search, params[:search] %><br>
    <%= submit_tag "Search", :name => nil %>
  </p>
<% end %>

<br>

<table>
	<% @users.try(:each) do |user| %>
		<tr>
			<td>
				<%= user.email %>
			</td>
			<td>
				<!-- If client is not already a client -->
				<% if !@clients.map(&:client_id).include?(user.id) && user != current_user %>	
					<%= button_to "Add as client", add_as_client_path(:client_id => user.id) %>
				<% else %>
					Already a client
				<% end -%>
			</td>
		</tr>
	<% end %>	
</table>

app/views/users/show.html.erb
<div class='section_break'>

	<% if @user.has_contact_info? %>
		<h1><%= @user.contact.title %> <%= @user.contact.fname %> <%= @user.contact.lname %></h1>
	<% end %>
	<h2><%= @user.email %></h2>
	<h3><%= @user.role.role %></h3>

	<% if can? :update, @contact %>
		<% if current_user.is_broker_of?(@user) || @user.is_current_user?(current_user) %>
			<%= link_to 'Update contact details', edit_contact_path(@user.contact) %><br>
		<% end %>
	<% end %>

</div>

<% if @user.is_broker? || @user.is_agent? %>
	<div class='section_break'>
		<% if !@extra.nil? %>
		
			<h2>Branch</h2>
			<h4><%= @extra.branch %></h4>

			<%= image_tag @extra.logo.url(:med) %><br>

			<%= link_to 'edit details', edit_user_extra_detail_path(@user, @extra) %>

		<% else %>

			<%= link_to 'Add Brand Details', new_user_extra_detail_path(@user) %>

		<% end %>
	</div>
<% end %>

<div class='section_break'>
	<h3>Contact Address</h3>

	<% if !@user.contact.contact_addresses.empty? %>

		<% @contact_addresses.each do |add|  %>
			<% if @contact_addresses.count == 1 %>
				<div class="note">
					<%= add.address_one %><br>
					<%= add.address_two %><br>
					<%= add.town %><br>
					<%= add.post_code %><br>

					<% if current_user.is_broker_of?(@user) %>
						<%= link_to 'Edit', edit_contact_contact_address_path(@user.contact, add) %>
					<% end -%>

				</div>
			<% elsif add.primary? %>
				<div class="note">
					<%= add.address_one %><br>
					<%= add.address_two %><br>
					<%= add.town %><br>
					<%= add.post_code %><br>

					<% if current_user.is_broker_of?(@user) %>
						<%= link_to 'Edit', edit_contact_contact_address_path(@user.contact, add) %>
					<% end -%>

				</div>
			<% end -%>
		<% end -%>

		<% if @user.contact.contact_addresses.count > 1 %>
			<%= link_to 'see all', contact_contact_addresses_path(@user.contact) %>
		<% end -%>

	<% else %>

		<h4>No Addresses stored</h4>

	<% end %>

	<% if can? :update, @contact_address %>
		<%= link_to 'Add address', new_contact_contact_address_path(@user.contact) %>
	<% end %>

</div>


<div class="section_break">

	<h3>Contact Numbers</h3>

	<% if !@numbers.empty? %>

		<table>
			
			<% @numbers.try(:each) do |number| %>
				
				<tr <% if number.is_primary? %>class="even"<% end -%> >
        			<td><% if number.is_primary? %><i class="fa fa-caret-right"></i><% end -%></td>
					<td><%= number.phone_type %></td>
					<td><b><%= number.phone_number %></b></td>
					<td>
						<%= link_to edit_contact_phone_number_path(@user.contact, number) do %>
							<i class="fa fa-cog fa-2x"></i>
						<% end %>
						<%= link_to [@user.contact, number], method: :delete, data: { confirm: 'Are you sure?' } do %>
							<i class="fa fa-times fa-2x"></i>
						<% end %>
					</td>
				</tr> 
			<% end %>
			
		</table>
	<% else  %>

		<h4>No numbers stored</h4>

	<% end %>
	
	<% if can? :update, @phone_number %>
		<%= link_to 'Add number', new_contact_phone_number_path(@user.contact) %><br>
	<% end %>

</div>

	<div class="section_break">

		<h3>Agent</h3>

		<h4><%= @agent.agent.contact.full_name if !@agent.nil? %></h4>

		<% if current_user.is_broker_of?(@user) || @user == current_user && current_user.is_broker? || @user == current_user && current_user.is_agent? %>
			<% if @agent.nil? %>
				<%= link_to "Assign agent", new_user_client_agent_path(@user) %>
			<% else %>
				<%= link_to "Edit agent", edit_user_client_agent_path(@user, @agent) %>
				<%= link_to 'Remove', @agent, method: :delete, data: { confirm: 'Are you sure?' } %>
			<% end -%>
		<% end -%>
	</div>
	

<% if @user == current_user %>
	<div class="section_break">

		<h3>Notification Settings</h3>

		<% if @user.mail_notification_setting.nil? %>
			<%= link_to 'New', new_user_mail_notification_setting_path( @user ) %>
		<% else %>
			<%= link_to 'Edit settings', edit_user_mail_notification_setting_path( @user, @user.mail_notification_setting) %>
		<% end -%>

	</div>
<% end -%>

<% if @user == current_user && current_user.is_broker? %>
	<div class="section_break">

		<h3>Color Pallete</h3>

		<% if !@user.global_setting.nil? %>
			<% if !@user.global_setting.color_one == '' %>
				<div class="color-block" style="background-color:<%= @global_setting.color_one %>">
					color one
				</div>
			<% end -%>

			<% if !@user.global_setting.color_two == '' %>
				<div class="color-block" style="background-color:<%= @global_setting.color_two %>">
					color two
				</div>
			<% end -%>

			<% if !@user.global_setting.color_three == '' %>
				<div class="color-block" style="background-color:<%= @global_setting.color_three %>">
					color three
				</div>
			<% end -%>
		<% end -%>

		<% if @user.global_setting.nil? %>
			<%= link_to 'New', new_user_global_setting_path( @user ) %>
		<% else %>
			<%= link_to 'Edit Pallette', edit_user_global_setting_path( @user, @user.global_setting) %>
		<% end -%>

	</div>
<% end -%>