config/routes.rb
Rails.application.routes.draw do
  
  resources :client_agents
  resources :mail_notification_settings
  resources :application_statuses
  resources :statuses
  # resources :lenders
  
  resources :clients do 
    get 'cases', on: :member
  end
  
  resources :applicants
  
  resources :contacts do 
    resources :contact_addresses
    resources :phone_numbers
  end
  
  resources :mortgage_addresses
  
  resources :case_requirements
  
  resources :requirements
  
  resources :notes
  
  resources :roles

  resources :application_cases do 
    resources :notes
    resources :case_requirements
    resources :applicants
    resources :application_statuses

    get 'edit_status', as: :edit_status
    get 'my_cases', as: :my_cases, on: :collection
    get '/search_agents' => 'application_cases#search_agents'
    post '/add_as_agent' => 'application_cases#add_as_agent' 
    get 'find_client', as: :find_client, on: :member
    post '/add_as_applicant' => 'application_cases#add_as_applicant'

  end

  resources :users do
    resources :application_cases
    resources :extra_details  
    resources :mail_notification_settings
    resources :client_agents
    resources :global_settings
    
    collection do 
      get 'clients_index',  as: :show_clients
      get 'agents_index',   as: :show_agents
    end
  end
  
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users, :path_prefix => 'my'

  # Additional users Routes
  get '/add_new_client' => 'users#add_new_client'

  # Additional Application Routes
  get '/client_cases' => 'application_cases#client_cases'
  get '/my_cases' => 'application_cases#index'
  get '/my_cases/:id' => 'application_cases#show'
  get '/new_case' => 'application_cases#new'
  get '/case_archive' => 'application_cases#case_archive'

  get '/search_users' => 'users#search_users'
  post '/add_as_client' => 'users#add_as_client'

  post '/send_email_notification' => 'notes#send_email_notification'
  post '/send_email_requirements_notification' => 'case_requirements#send_email_requirements_notification'


  get '/my_clients' => 'client_agents#index'

  # Root path
  root 'statics#index' 


end

app/models/mail_notification_setting.rb
class MailNotificationSetting < ActiveRecord::Base
  belongs_to :user
end

app/controllers/mail_notification_settings_controller.rb
class MailNotificationSettingsController < ApplicationController
  before_action :set_mail_setting, only: [:show, :edit, :update, :destroy]
  before_action :set_user, only: [:new, :index, :show, :create, :edit, :update, :destroy]

  def new
  	@mail_notification_setting = MailNotificationSetting.new
  end

  def edit
  end

  # POST /Contacts
  # POST /Contacts.json
  def create
    @extra_detail = @user.build_mail_notification_setting(mail_notification_setting_params)

    respond_to do |format|
      if @extra_detail.save
        format.html { redirect_to @user, notice: 'Detail was successfully created.' }
        format.json { render :show, status: :created, location: @contact_address }
      else
        format.html { render :new }
        format.json { render json: @extra_detail.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /roles/1
  # PATCH/PUT /roles/1.json
  def update
    respond_to do |format|
      if @mail_notification_setting.update(mail_notification_setting_params)
        format.html { redirect_to @user, notice: 'Detail was successfully updated.' }
        format.json { render :show, status: :ok, location: @extra_detail }
      else
        format.html { render :edit }
        format.json { render json: @mail_notification_setting.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /roles/1
  # DELETE /roles/1.json
  def destroy
    @mail_notification_setting.destroy
    respond_to do |format|
      format.html { redirect_to @mail_setting.user, notice: 'Detail was successfully destroyed.' }
      format.json { head :no_content }
    end
  end
  
  private

    def set_user
      @user = User.find(params[:user_id])
    end
 
  	def set_mail_setting
  		@mail_notification_setting = MailNotificationSetting.find(params[:id])
  	end

    def mail_notification_setting_params
      params.require(:mail_notification_setting).permit(:notes, :all_emails, :daily_digest, :status_update, :user_id, :requirement_alerts)
    end
end

app/helpers/mail_notification_settings_helper.rb
module MailNotificationSettingsHelper
end

app/views/mail_notification_settings/_form.html.erb
<%= form_for([@user, @mail_notification_setting]) do |f| %>

  <% if @mail_notification_setting.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@mail_notification_setting.errors.count, "error") %> prohibited this mail_notification_setting from being saved:</h2>

      <ul>
      <% @mail_notification_setting.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <p>Click the the checkbox to opt out fo the following:</p>

  <div class="field">
    <%= f.label :all_emails, "All Email notifications" %>
    <%= f.check_box :all_emails %>
  </div>

  <% if current_user.is_broker? %>
    <div class="field">
      <%= f.label :notes, 'Note notifications' %>
      <%= f.check_box :notes %>
    </div>
  <% end -%>
  <div class="field">
    <%= f.label :requirement_alerts, 'Case requirement notifications' %>
    <%= f.check_box :requirement_alerts %>
  </div>
  <div class="field">
    <%= f.label :daily_digest, 'Daily Digest emails' %>
    <%= f.check_box :daily_digest %>
  </div>
  <div class="field">
    <%= f.label :status_update, 'Status update notifications' %>
    <%= f.check_box :status_update %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/mail_notification_settings/edit.html.erb
<h1>Editing Mail Notification Setting</h1>

<%= render 'form' %>

app/views/mail_notification_settings/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Mail Notification Settings</h1>

<table>
  <thead>
    <tr>
      <th>Notes</th>
      <th>All emails</th>
      <th>Daily digest</th>
      <th>Status update</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @mail_notification_settings.each do |mail_notification_setting| %>
      <tr>
        <td><%= mail_notification_setting.notes %></td>
        <td><%= mail_notification_setting.all_emails %></td>
        <td><%= mail_notification_setting.daily_digest %></td>
        <td><%= mail_notification_setting.status_update %></td>
        <td><%= mail_notification_setting.user %></td>
        <td><%= link_to 'Show', mail_notification_setting %></td>
        <td><%= link_to 'Edit', edit_mail_notification_setting_path(mail_notification_setting) %></td>
        <td><%= link_to 'Destroy', mail_notification_setting, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Mail notification setting', new_mail_notification_setting_path %>

app/views/mail_notification_settings/new.html.erb
<h1>Mail Notification Settings</h1>

<%= render 'form' %>

app/views/mail_notification_settings/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Notes:</strong>
  <%= @mail_notification_setting.notes %>
</p>

<p>
  <strong>All emails:</strong>
  <%= @mail_notification_setting.all_emails %>
</p>

<p>
  <strong>Daily digest:</strong>
  <%= @mail_notification_setting.daily_digest %>
</p>

<p>
  <strong>Status update:</strong>
  <%= @mail_notification_setting.status_update %>
</p>

<p>
  <strong>User:</strong>
  <%= @mail_notification_setting.user %>
</p>

<%= link_to 'Edit', edit_mail_notification_setting_path(@mail_notification_setting) %> |
<%= link_to 'Back', mail_notification_settings_path %>